"""вернул на место

Revision ID: 2b6532f0c1fb
Revises: 6ae357bf3f02
Create Date: 2025-09-07 02:03:47.842229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b6532f0c1fb'
down_revision: Union[str, Sequence[str], None] = '6ae357bf3f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_client_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'client_id')
    op.add_column('clients', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'appointments', ['appointment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'appointment_id')
    op.add_column('appointments', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('appointments_client_id_fkey'), 'appointments', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
