"""поменял связь клиентов и  апоинтментов

Revision ID: 6ae357bf3f02
Revises: 8dc60b82aca0
Create Date: 2025-09-07 02:01:49.955365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae357bf3f02'
down_revision: Union[str, Sequence[str], None] = '8dc60b82aca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'clients', ['client_id'], ['id'])
    op.drop_constraint(op.f('clients_appointment_id_fkey'), 'clients', type_='foreignkey')
    op.drop_column('clients', 'appointment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('clients_appointment_id_fkey'), 'clients', 'appointments', ['appointment_id'], ['id'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'client_id')
    # ### end Alembic commands ###
