"""new payment cols

Revision ID: ad29bbb85a2a
Revises: 49b80bec6d94
Create Date: 2025-09-07 17:07:46.503596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad29bbb85a2a'
down_revision: Union[str, Sequence[str], None] = '49b80bec6d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('course', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('type_of_payment', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('type_of_massage', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('service', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('visit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'visit')
    op.drop_column('appointments', 'service')
    op.drop_column('appointments', 'duration')
    op.drop_column('appointments', 'type_of_massage')
    op.drop_column('appointments', 'type_of_payment')
    op.drop_column('appointments', 'discount')
    op.drop_column('appointments', 'course')
    op.drop_column('appointments', 'price')
    # ### end Alembic commands ###
