"""add expenses table and update appointments and clients

Revision ID: b1036529afdf
Revises: e2401a34b133
Create Date: 2025-09-06 20:01:00.103804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1036529afdf'
down_revision: Union[str, Sequence[str], None] = 'e2401a34b133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('expense', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointments', sa.Column('is_finished', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('email', sa.String(length=320), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'email')
    op.drop_column('clients', 'phone')
    op.drop_column('appointments', 'is_finished')
    op.drop_table('expenses')
    # ### end Alembic commands ###
