"""client_id

Revision ID: c7729b89a469
Revises: 2b6532f0c1fb
Create Date: 2025-09-07 13:12:12.546985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7729b89a469'
down_revision: Union[str, Sequence[str], None] = '2b6532f0c1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'clients', ['client_id'], ['id'])
    op.drop_constraint(op.f('clients_appointment_id_fkey'), 'clients', type_='foreignkey')
    op.drop_column('clients', 'appointment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('clients_appointment_id_fkey'), 'clients', 'appointments', ['appointment_id'], ['id'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'client_id')
    # ### end Alembic commands ###
