"""rename clients to client in appointments

Revision ID: de8e357e8b97
Revises: b1036529afdf
Create Date: 2025-09-07 01:12:24.433399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8e357e8b97'
down_revision: Union[str, Sequence[str], None] = 'b1036529afdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'appointment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'appointment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
